<?php

namespace App\Imports;

use App\Models\Planeacion;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class ExcelImport implements ToModel, WithHeadingRow
{
    public function model(array $row)
    {
        return new Planeacion([
            'Cuenta'                 => $row['cuenta'] ?? null,
            'Salon'                  => $row['salon'] ?? null,
            'Telar'                  => $row['telar'] ?? null,
            'Ultimo'                 => $row['ultimo'] ?? null,
            'Cambios_Hilo'           => $row['cambios_hilo'] ?? null,
            'Maquina'                => $row['maquina'] ?? null,
            'Ancho'                  => $row['ancho'] ?? null,
            'Eficiencia_Std'         => $row['eficiencia_std'] ?? null,
            'Velocidad_STD'          => $row['velocidad_std'] ?? null,
            'Hilo'                   => $row['hilo'] ?? null,
            'Calibre_Rizo'           => $row['calibre_rizo'] ?? null,
            'Calibre_Pie'            => $row['calibre_pie'] ?? null,
            'Calendario'             => $row['calendario'] ?? null,
            'Clave_Estilo'           => $row['clave_estilo'] ?? null,
            'Tamano_AX'              => $row['tamano_ax'] ?? null,
            'Estilo_Alternativo'     => $row['estilo_alternativo'] ?? null,
            'Nombre_Producto'        => $row['nombre_producto'] ?? null,
            'Saldos'                 => $row['saldos'] ?? null,
            'Fecha_Captura'          => $row['fecha_captura'] ?? null,
            'Orden_Prod'             => $row['orden_prod'] ?? null,
            'Fecha_Liberacion'       => $row['fecha_liberacion'] ?? null,
            'Id_Flog'                => $row['id_flog'] ?? null,
            'Descrip'                => $row['descrip'] ?? null,
            'Aplic'                  => $row['aplic'] ?? null,
            'Obs'                    => $row['obs'] ?? null,
            'Tipo_Ped'               => $row['tipo_ped'] ?? null,
            'Tiras'                  => $row['tiras'] ?? null,
            'Peine'                  => $row['peine'] ?? null,
            'Largo_Crudo'            => $row['largo_crudo'] ?? null,
            'Peso_Crudo'             => $row['peso_crudo'] ?? null,
            'Luchaje'                => $row['luchaje'] ?? null,
            'CALIBRE_TRA'            => $row['calibre_tra'] ?? null,
            'Dobladillo'             => $row['dobladillo'] ?? null,
            'PASADAS_TRAMA'          => $row['pasadas_trama'] ?? null,
            'PASADAS_C1'             => $row['pasadas_c1'] ?? null,
            'PASADAS_C2'             => $row['pasadas_c2'] ?? null,
            'PASADAS_C3'             => $row['pasadas_c3'] ?? null,
            'PASADAS_C4'             => $row['pasadas_c4'] ?? null,
            'PASADAS_C5'             => $row['pasadas_c5'] ?? null,
            'ancho_por_toalla'       => $row['ancho_por_toalla'] ?? null,
            'COLOR_TRAMA'            => $row['color_trama'] ?? null,
            'CALIBRE_C1'             => $row['calibre_c1'] ?? null,
            'Clave_Color_C1'         => $row['clave_color_c1'] ?? null,
            'COLOR_C1'               => $row['color_c1'] ?? null,
            'CALIBRE_C2'             => $row['calibre_c2'] ?? null,
            'Clave_Color_C2'         => $row['clave_color_c2'] ?? null,
            'COLOR_C2'               => $row['color_c2'] ?? null,
            'CALIBRE_C3'             => $row['calibre_c3'] ?? null,
            'Clave_Color_C3'         => $row['clave_color_c3'] ?? null,
            'COLOR_C3'               => $row['color_c3'] ?? null,
            'CALIBRE_C4'             => $row['calibre_c4'] ?? null,
            'Clave_Color_C4'         => $row['clave_color_c4'] ?? null,
            'COLOR_C4'               => $row['color_c4'] ?? null,
            'CALIBRE_C5'             => $row['calibre_c5'] ?? null,
            'Clave_Color_C5'         => $row['clave_color_c5'] ?? null,
            'COLOR_C5'               => $row['color_c5'] ?? null,
            'Plano'                  => $row['plano'] ?? null,
            'Cuenta_Pie'             => $row['cuenta_pie'] ?? null,
            'Clave_Color_Pie'        => $row['clave_color_pie'] ?? null,
            'Color_Pie'              => $row['color_pie'] ?? null,
            'Peso_gr_m2'             => $row['peso_gr_m2'] ?? null,
            'Dias_Ef'                => $row['dias_ef'] ?? null,
            'Prod_Kg_Dia'            => $row['prod_kg_dia'] ?? null,
            'Std_Dia'                => $row['std_dia'] ?? null,
            'Prod_Kg_Dia1'           => $row['prod_kg_dia1'] ?? null,
            'Std_Toa_Hr_100'         => $row['std_toa_hr_100'] ?? null,
            'Dias_jornada_completa'  => $row['dias_jornada_completa'] ?? null,
            'Horas'                  => $row['horas'] ?? null,
            'Std_Hr_efectivo'        => $row['std_hr_efectivo'] ?? null,
            'Inicio_Tejido'          => $row['inicio_tejido'] ?? null,
            'Calc4'                  => $row['calc4'] ?? null,
            'Calc5'                  => $row['calc5'] ?? null,
            'Calc6'                  => $row['calc6'] ?? null,
            'Fin_Tejido'             => $row['fin_tejido'] ?? null,
            'Fecha_Compromiso'       => $row['fecha_compromiso'] ?? null,
            'Fecha_Compromiso1'      => $row['fecha_compromiso1'] ?? null,
            'Entrega'                => $row['entrega'] ?? null,
            'Dif_vs_Compromiso'      => $row['dif_vs_compromiso'] ?? null,
            'en_proceso'             => $row['en_proceso'] ?? null,
            'id'                     => $row['id'] ?? null,
            'cantidad'               => $row['cantidad'] ?? null,
            'Clave_AX'               => $row['clave_ax'] ?? null,
        ]);
    }
}
