<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Modelos extends Model
{
    use HasFactory;

    protected $table = 'modelos'; // Nombre de la tabla

    // Especificamos los atributos de la tabla
    protected $fillable = [
        'TITULO_TEMP',
        'RASEMA',
        'Fecha_Orden',
        'Fecha_Cumplimiento',
        'Departamento',
        'Telar_Actual',
        'Prioridad',
        'Modelo',
        'CLAVE_MODELO',
        'CLAVE_AX',
        'TOLERANCIA',
        'CODIGO_DE_DIBUJO',
        'Fecha_Compromiso',
        'Nombre_de_Formato_Logistico',
        'Clave',
        'Cantidad_a_Producir',
        'Peine',
        'Ancho',
        'Largo',
        'P_crudo',
        'Luchaje',
        'Tra',
        'Hilo',
        'OBS#',
        'Tipo_plano',
        'Med_plano',
        'TIPO_DE_RIZO',
        'ALTURA_DE_RIZO',
        'OBS',
        'Veloc#_Minima',
        'Rizo',
        'Hilo1',
        'CUENTA',
        'OBS#1',
        'Pie',
        'Hilo2',
        'CUENTA1',
        'OBS#2',
        'C1',
        'OBS1',
        'C2',
        'OBS2',
        'C3',
        'OBS3',
        'C4',
        'OBS4',
        'Med#_de_Cenefa',
        'Med_de_inicio_de_rizo_a_cenefa',
        'RAZURADA',
        'TIRAS',
        'Repeticiones_p_corte',
        'No#_De_Marbetes',
        'Cambio_de_repaso',
        'Vendedor',
        'No#_Orden',
        'Observaciones',
        'TRAMA_(Ancho_Peine)',
        'LOG#_DE_LUCHA_TOTAL',
        'C1___trama_de_Fondo',
        'Hilo3',
        'OBS#3',
        'PASADAS',
        'C11',
        'Hilo4',
        'OBS#4',
        'PASADAS1',
        'C21',
        'Hilo5',
        'OBS#5',
        'PASADAS2',
        'C31',
        'Hilo6',
        'OBS#6',
        'PASADAS3',
        'C41',
        'Hilo7',
        'OBS#7',
        'PASADAS4',
        'C5',
        'Hilo8',
        'OBS#8',
        'x',
        'TOTAL',
        'PASADAS_DIBUJO',
        'Contraccion',
        'Tramas_cm_Tejido',
        'Contrac_Rizo',
        'Clasificación_KG',
        'KG_x_Dia',
        'Densidad',
        'Pzas_Dia__pasadas',
        'Pzas_Día_formula',
        'DIF',
        'EFIC#',
        'Rev',
        'TIRAS1',
        'PASADAS5',
        'A',
        'B',
        'C',
        'COMPROBAR_modelos_duplicados',
    ];

    public $timestamps = false; // Si no usas los timestamps (created_at y updated_at)
}
