<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Modelos extends Model
{
    use HasFactory;

    protected $table = 'modelos'; // Nombre de la tabla

    // Especificamos los atributos de la tabla
    protected $fillable = [
        'NOMBRE',
        'RASEMA',
        'Fecha_Orden',
        'Fecha_Cumplimiento',
        'Departamento',
        'Telar_Actual',
        'Prioridad',
        'Modelo',
        'CLAVE_MODELO',
        'CLAVE_AX',
        'TOLERANCIA',
        'CODIGO_DE_DIBUJO',
        'Fecha_Compromiso',
        'Nombre_de_Formato_Logistico',
        'Clave',
        'Cantidad_A_Producir',
        'Peine',
        'Ancho',
        'Largo',
        'P_crudo',
        'Luchaje',
        'Tra',
        'Hilo',
        'OBS',
        'Tipo_plano',
        'Med_plano',
        'TIPO_DE_RIZO',
        'ALTURA_DE_RIZO',
        'OBS2',
        'Veloc_Minima',
        'Rizo',
        'Hilo_1',
        'CUENTA',
        'OBS3',
        'Pie',
        'Hilo_2',
        'CUENTA1',
        'OBS4',
        'C1',
        'OBS_C1',
        'C2',
        'OBS_C2',
        'C3',
        'OBS_C3',
        'C4',
        'OBS_C4',
        'Med#_de_Cenefa',
        'Med_de_inicio_de_rizo_a_cenefa',
        'RAZURADA',
        'TIRAS',
        'Repeticiones_p_corte',
        'No_De_Marbetes',
        'Cambio_de_repaso',
        'Vendedor',
        'No_Orden',
        'Observaciones',
        'TRAMA_Ancho_Peine',
        'LOG_DE_LUCHA_TOTAL',
        'C1_trama_de_Fondo',
        'Hilo_3',
        'OBS_R1',
        'PASADAS',
        'C1_R',
        'Hilo_4',
        'OBS_R2',
        'PASADAS_C1',
        'C2_R',
        'Hilo_5',
        'OBS_R3',
        'PASADAS_C2',
        'C3_R',
        'Hilo_6',
        'OBS_R4',
        'PASADAS_C3',
        'C4_R',
        'Hilo_7',
        'OBS_R5',
        'PASADAS_C4',
        'C5_R',
        'Hilo_8',
        'OBS_R6',
        'X',
        'TOTAL',
        'PASADAS_DIBUJO',
        'Contraccion',
        'Tramas_cm_Tejido',
        'Contrac_Rizo',
        'Clasificacion_KG',
        'KG_Dia',
        'Densidad',
        'Pzas_Dia_pasadas',
        'Pzas_Dia_formula',
        'DIF',
        'EFIC',
        'Rev',
        'TIRAS_2',
        'PASADAS_F',
        'A',
        'B',
        'C',
        'COMPROBAR_modelos_duplicados',
    ];
    

    public $timestamps = false; // Si no usas los timestamps (created_at y updated_at)
}
